### ISSUE TITLE
Quark should only generate code that's actively used

### ISSUE THREAD

**Issue by janicedatawire** [datawire/quark#11]
Some building block code is getting generated whether or not it's actively used. For example, the python generator currently includes the following in every generated .py file whether or not lists and maps are used:

```
_Map = dict
class _List(list):
    def __repr__(self):
        return "[%s]" % ", ".join([str(e) for e in self])
```

**Comment by bozzzzo** [comment]
all of that is now one tidy `from quark_runtime import *`
