### ISSUE TITLE
Make the Quark compiler console output less noisy

### ISSUE THREAD

**Issue by brikelly** [datawire/quark#111]
The Quark compiler currently spits out a lot of noisy output as it emits code, does pip installs, etc. It would be great to move that noisy output to a non-default "verbose" mode and instead make the default much quieter. 

Here's a suggestion for the output: 

Parsing Quark code…done.
Emitting Python code….done.
Installing in PIP….done.
Done.

**Comment by janicedatawire** [comment]
I would also include the following (assuming doc gen is part of install):

`Generating documentation....done.`
