### ISSUE TITLE
Quark compiles with package-internal references to package names but the resulting code doesn't work

### ISSUE THREAD

**Issue by janicedatawire** [datawire/quark#22]
If I reference another class in the current package using package.class notation, Quark accepts it and spits out generated code. However, that code will not compile and/or run in any of the languages.

See attached file for an example. 
[convertUnits2.txt](https://github.com/datawire/quark/files/13280/convertUnits2.txt)

The code generated by that file throws the following Python errors:

```
$ python convertUnits2.py
Traceback (most recent call last):
  File "convertUnits2.py", line 16, in <module>
    main()
  File "convertUnits2.py", line 10, in main
    conversion = convert2.Conversion();
  File "/Users/janicekarin/quark-examples/python/convert2/__init__.py", line 47, in __init__
    def __init__(self): self._init()
  File "/Users/janicekarin/quark-examples/python/convert2/__init__.py", line 44, in _init
    self.conversionFactors = convert2.ConversionFactors()
NameError: global name 'convert2' is not defined
```

Either the Quark compiler should complain about these references or it should generate code that works in the supported languages when they are present.

**Comment by bozzzzo** [comment]
Seems to be resolved in recent python
