### ISSUE TITLE
Quark doesn't support compound if conditionals because it doesn't support && and || for integers

### ISSUE THREAD

**Issue by janicedatawire** [datawire/quark#24]
Quark uses 1/0 for true/false. They are treated as integers. && and || are not supported for integers. As a consequence, statements like the following are not supported:

`if (input.type=="length" && output.type=="length"){...}`

If you try to use them, the compiler throws this error for all languages:

foo.q:36:16:int has no such attribute: __and__

You can work around this for && by nesting if statements as follows:

```
if (input.type=="length"){
    if (output.type=="length"){
         ...
    }
}
```

Note: Issue #3 requests support for booleans. If that issue is addressed, the lack of && and || support becomes less important (and possibly irrelevant) as it no longer impedes if statement construction.

**Comment by rhs** [comment]
This should be fixed now.
