### ISSUE TITLE
Declaring variables before they are used results in errors in the generated Python code

### ISSUE THREAD

**Issue by janicedatawire** [datawire/quark#25]
When I declare variables before assigning them values within main(), the Quark compiler generates code in all three languages and the Javascript and Java code works as expected. Python, however, gives the following error:

```
$ python usingMacros.py
Traceback (most recent call last):
  File "usingMacros.py", line 13, in <module>
    main()
  File "usingMacros.py", line 5, in main
    latitude;
UnboundLocalError: local variable 'latitude' referenced before assignment
```

If I change the code so that the variables are declared at the same time they are assigned, all three languages are happy and the code works.

usingMacros.q declares variables up front, usingMacros2.q declares them at assignment. Both use a macro defined in macros.q.

[macros.txt](https://github.com/datawire/quark/files/15334/macros.txt)
[usingMacros.txt](https://github.com/datawire/quark/files/15335/usingMacros.txt)
[usingMacros2.txt](https://github.com/datawire/quark/files/15336/usingMacros2.txt)

Note: I have successfully declared before assignment inside class definitions.

**Comment by bozzzzo** [comment]
Fixed in recent quark
