### ISSUE TITLE
@doc directives above methods are not translated into the Javadoc

### ISSUE THREAD

**Issue by janicedatawire** [datawire/quark#46]
@doc directives for packages, classes, and properties appear to be working but @doc directives for methods are currently ignored.

The package description is also missing. For info on how to set it, see the following:

http://docs.oracle.com/javase/specs/jls/se7/html/jls-7.html#jls-7.4.1

**Comment by bozzzzo** [comment]
Doc directives for methods seem to get generated to javadoc now.
Doc directives for fields seem to not be generated for python.
Doc directives for packages seem not to get generated, will open a new issue.
