### ISSUE TITLE
Interface not resolving in generated Java code

### ISSUE THREAD

**Issue by janicedatawire** [datawire/quark#55]
I have a Quark file with an interface containing two method signatures and a default method printe() that prints 2.718.

I use the interface in class Unit2 and then execute printe() from a Unit2 object within main().

The line prints in Javascript and Python but Java throws the following error:

```
$ javac Functions.java
./convert/Unit2.java:3: error: cannot find symbol
public class Unit2 implements foobar {
                              ^
  symbol: class foobar
1 error
```

Note: I did not add definitions for the method signatures in the interface within Unit2 and expected Java to complain about trying to instantiate abstract classes with this code, but I'm not getting to that point

**Comment by bozzzzo** [comment]
Not enough context to reproduce
