### ISSUE TITLE
Names of user packages generated for Java and Python incorrect in documentation

### ISSUE THREAD

**Issue by jmkarin** [datawire/quark#80]
The section describing the output of the package command lists the expected package names for each output language here:

http://datawire.github.io/quark/install/compile.html#package

Both Java and Python have a 0.1.0 string in the naming pattern. This is actually a variable set using the first @version annotation encountered starting from the top of the first file in the compile list then continuing through the files in order until the end of the last file specified.

The documentation needs to be updated to reflect this and also to indicate what happens if no @version annotation is found.

**Comment by janicedatawire** [comment]
This has been fixed locally and will be in the next release.

**Comment by jmkarin** [comment]
The fix has been published in 0.2.8-1
