### ISSUE TITLE
Numeric types missing >= and <= operators

### ISSUE THREAD

**Issue by plombardi89** [datawire/quark#95]
Looks like all numeric types are missing two fairly useful operators:

hub_v2.q:510:28:int has no such attribute: __ge__
hub_v2.q:510:50:int has no such attribute: __le__
hub_v2.q:511:28:int has no such attribute: __ge__
hub_v2.q:511:50:int has no such attribute: __le__

Caused here:

```java
        void onError(message.HubError error) {
            if (error.code >= 1000 && error.code <= 1999) { self.onServerError(error); }
            if (error.code >= 2000 && error.code <= 2999) { self.onClientError(error); }
        }
```

**Comment by ark3** [comment]
Fixed at some point, test added in cf6b6f5
